// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'ap-southeast-2',
  aws_dynamodb_all_tables_region: 'ap-southeast-2',
  aws_dynamodb_table_schemas: [
    {
      tableName: 'dynamoe28012f0-dev',
      region: 'ap-southeast-2'
    }
  ],
  aws_cloud_logic_custom: [
    {
      name: 'api0d5db60e',
      endpoint:
        'https://fps2y966oe.execute-api.ap-southeast-2.amazonaws.com/dev',
      region: 'ap-southeast-2'
    }
  ],
  aws_cognito_identity_pool_id:
    'ap-southeast-2:6643bf5f-0cee-447a-bb53-b072d3a5ebfb',
  aws_cognito_region: 'ap-southeast-2',
  aws_user_pools_id: 'ap-southeast-2_0eJOGgalo',
  aws_user_pools_web_client_id: '299qdvrjnseiuf24b3480fpjcl',
  oauth: {},
  aws_mobile_analytics_app_id: 'cdb2dcd8e4254d8c83dab23f76b56986',
  aws_mobile_analytics_app_region: 'us-west-2'
};

export default awsmobile;
